### ISSUE TITLE
Introducing the new genus Mineirella in the subfamily Cheilanthoideae (Pteridaceae).

### ISSUE THREAD

**Issue by MoniPonce** [pteridogroup/ppg#8] opened 2023-05-30 20:42 UTC
### Name of taxon

Mineirella Ponce & Scataglini

### Rank of taxon

Genus

### Approximate number of species affected

Four species and one hybrid

### Description of change

Three Cheilanthes species (C. geraniifolia, C. goyazensis and C. bradei) from Northern, Central Western and South Eastern Brazil,  appear segregated from the Cheilanthes s. str. clade in our molecular phylogeny (Ponce & Scataglini, 2020). These species form a highly supported clade, which is included in the large Adiantopsis-Doryopteris clade. The three species plus two morphologically related taxa, C. eriophora and C. steyermarkii, were transferred to the new genus Mineirella Ponce & Scataglini (Dec/2020 on line).

Among the taxa related to Mineirella are the remaining Cheilanthes and Pellaea species from Africa and Madagascar, formerly named "Choristosoria grade" by Yesilyurt et al. (2015) and “Pteridellastrum” Prantl, unranked group (cfr. Ponce & Scataglini, 2020). The relationships between these Mineirella-related species need further analysis to be confirmed.

### Reason for change

The change proposed is supported by the molecular phylogenetic analysis. Also, the five species grow in xeric and semi-xeric habitats of basaltic rocks and sandstone substrates, and share the following morphological characteristics: rhizomes creeping, horizontal, elongate (vs. rhizomes ascending or decumbent, compact, in Cheilanthes); laminae pedate-lobate, pedate-pinnatifid, or pedate basally pinnate (vs.  laminae 1-4-pinnate in Cheilanthes).

### Reference(s) for publication of the name

[Ponce & Scataglini_2020_ Phylogeny of Cheilanthes.pdf](https://github.com/pteridogroup/ppg/files/11604868/Ponce.Scataglini_2020_.Phylogeny.of.Cheilanthes.pdf)

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by joelnitta** [comment] 2023-08-29 22:28
This is a duplicate of #40 (it was mistakenly hidden due to a GitHub glitch for some period of time, during which the voting window closed).

**Closed by joelnitta** 2023-08-29 22:28 UTC
