### ISSUE TITLE
The generic circumscription of Cheilanthes Sw. (Cheilanthoideae, Pteridaceae)

### ISSUE THREAD

**Issue by MoniPonce** [pteridogroup/ppg#7] opened 2023-05-30 20:01 UTC
### Name of taxon

Cheilanthes Sw.

### Rank of taxon

Genus

### Approximate number of species affected

70

### Description of change

From a total of about 100 species of Cheilanthes s.l. , in PPG I (2016), about 70 of them would belong to the s. str. clade, distributed in South America, Australasia, Africa, and Madagascar.
In our recent studies (Ponce & Scataglini, 2020), in order to examine the phylogenetic position of Cheilanthes species from South America, we reconstructed a representative molecular phylogeny of the hemionitioid clade. As a result, from a total of ca. 35 South American Cheilanthes species, more than 20 of them appeared in the Cheilanthes s. str. clade with maximum support. We propose that the Cheilanthes s. str. clade contains three subclades: 1) exclusively South American species (≈10 spp.), 2) Australasia + ≈16 South American species, including the type C. micropteris, and 3) exclusively African and Madagascar species. Recently, Cheilanthes volcanensis de la Sota, a poorly known species restricted to North-western Argentina and Bolivia, was also confirmed in the exclusive South America clade (Ponce et al. 2023). 
On the other hand, three Cheilanthes species (C. geraniifolia, C. goyazensis and C. bradei) from Northern, Central Western and South Eastern Brazil, appear segregated from the Cheilanthes s. str. clade in our phylogeny. These three species plus two morphologically related taxa, C. eriophora and C. steyermarkii, were transferred to the new genus Mineirella Ponce & Scataglini (2020). (see Mineirella proposal)

### Reason for change

The hemionitioid group is composed of three highly supported main clades: 1)Cheilanthes s. str., 2)Hemionitis clade + “Pteridella” group (from Africa and Madagascar), and 3)Adiantopsis – Doryopteris clade, which also include neotropical (e.g. Mineirella) and paleotropical (e.g. Choristosoria) species groups. The relationships between these three main clades were showed in previous works but they have not been fully resolved yet (Eisenhardt et al. 2011; Yesilyurt et al. 2015, Ponce & Scataglini, 2018; 2020). 
The Cheilanthes s. str. is morphologically heterogeneous, but presents diagnostic characters that difference it from the remaining cheilantoids ferns : concolor rhizomatic scales (vs. bicolor rhizomatic scales in Adiantopsis, Doryopteris, Mineirella); free veins, apically widened (vs. not or slightly widened vein tips in Myriopteris), sporangia at the vein tips (vs. along the veins in Hemionitis); elongated cordiform or ribbon like, glabrous gametophytes (vs. pilose gametophytes in Hemionitis, and farinose glandular gametophytes in Notholaena). Root anatomy with whole cortex thinned cell walls or gradually thickened cell walls and wide lumen (vs. inner cortex with strongly thickened cell walls and narrow lumen in Adiantopsis, Doryopteris and Mineirella) (cfr. Hernández, 2019 Thesis). Also, the Australasian-South American Cheilanthes subclade presents exclusively 32 small spores per sporangium, in sexual condition (vs. 64 small spores per sporangium in sexual condition, present in most of the cheilanthoids species) (cfr. Gruzs & Windham, 2013; Ponce & Scataglini, 2018, 2020).

### Reference(s) for publication of the name

[Ponce & Scataglini_2020_ Phylogeny of Cheilanthes.pdf](https://github.com/pteridogroup/ppg/files/11604713/Ponce.Scataglini_2020_.Phylogeny.of.Cheilanthes.pdf)

[Ponce et al. 2023.pdf](https://github.com/pteridogroup/ppg/files/11604756/Ponce.et.al.2023.pdf)

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by joelnitta** [comment] 2023-08-29 22:27
This is a duplicate of #39 (it was mistakenly hidden due to a GitHub glitch for some period of time, during which the voting window closed).

**Closed by joelnitta** 2023-08-29 22:27 UTC
